バグ修正

diff --git a/sample/Makefile b/sample/Makefile
--- a/sample/Makefile
+++ b/sample/Makefile
@@ -11,31 +11,31 @@ TFPLAN_DIR := $(SCRIPT_DIR)/.tfplan/$(COMPONENT)/
 .PHONY: option-parser
 option-parser:
 	@if [ -z "$(PROJECT_NAME)" ]; then \
-		echo "[Err] PROJECT_NAME is required"; \
-		exit 1; \
+	  echo "[Err] PROJECT_NAME is required"; \
+	  exit 1; \
 	fi
 	@if [ -z "$(STAGE)" ]; then \
-		echo "[Err] STAGE is required"; \
-		exit 1; \
+	  echo "[Err] STAGE is required"; \
+	  exit 1; \
 	fi
 	@if [ -z "$(COMPONENT)" ]; then \
-		echo "[Err] COMPONENT is required"; \
-		exit 1; \
+	  echo "[Err] COMPONENT is required"; \
+	  exit 1; \
 	fi
 
 .PHONY: tf-validate 
-tf-validate: option-parser ## terraform validate
+tf-validate: tf-init  ## terraform validate
 	terraform -chdir=$(COMPONENT_DIR) validate
 
 .PHONY: tf-init
-tf-init: tf-validate ## terraform init
+tf-init: option-parser ## terraform init
 	terraform -chdir=$(COMPONENT_DIR) init \
 	  -reconfigure \
 	  -backend-config $(COMMON_BACKEND_CONFIG) \
 	  -backend-config "key=$(PROJECT_NAME)/$(STAGE)/$(COMPONENT)/terraform.tfstate"
 
 .PHONY: tf-plan
-tf-plan: tf-init ## terraform plan
+tf-plan: tf-validate ## terraform plan
 	mkdir -p $(TFPLAN_DIR)
 	terraform -chdir=$(COMPONENT_DIR) plan \
 	  -var "project_name=$(PROJECT_NAME)" \
@@ -46,26 +46,26 @@ tf-plan: tf-init ## terraform plan
 	terraform -chdir=$(COMPONENT_DIR) show -json $(TFPLAN_DIR)/.plan > $(TFPLAN_DIR)/plan.tfgraph
 
 .PHONY: tf-apply
-tf-apply: tf-init ## terraform apply
+tf-apply: tf-validate ## terraform apply
 	terraform -chdir=$(COMPONENT_DIR) apply \
 	  -var "project_name=$(PROJECT_NAME)" \
 	  -var "stage=$(STAGE)" \
 	  -var-file=$(COMMON_TFVARS) \
 	  -var-file $(COMPONENT_TFVARS) \
-		--auto-approve
+	  --auto-approve
 
 .PHONY: tf-output
-tf-output: tf-init ## terraform apply
+tf-output: tf-validate ## terraform apply
 	terraform -chdir=$(COMPONENT_DIR) output
 
 .PHONY: tf-destroy
-tf-destroy: tf-init ## terraform destroy
+tf-destroy: tf-validate ## terraform destroy
 	terraform -chdir=$(COMPONENT_DIR) destroy \
 	  -var "project_name=$(PROJECT_NAME)" \
 	  -var "stage=$(STAGE)" \
 	  -var-file=$(COMMON_TFVARS) \
 	  -var-file $(COMPONENT_TFVARS) \
-		--auto-approve
+	  --auto-approve
 
 .PHONY: help
 .DEFAULT_GOAL := help
